# .streamlit/config.toml

[logger]
# Only show messages at “error” level or above (hides lower-level warnings)
level = "error"

# Import miniLM from external source like Google Drive
gdrive_model_id = "YOUR_DRIVE_FILE_ID_HERE"
