# .streamlit/config.toml

[logger]
# Import miniLM from external source like Google Drive
gdrive_model_id = "13Wcqq5uZkBrSARcbLPZHrXqTiE9XfGsp"

# Only show messages at “error” level or above (hides lower-level warnings)
level = "error"
